# coding: utf-8

"""
    Masking API

    Schema for the Continuous Compliance Engine API  # noqa: E501

    OpenAPI spec version: 5.1.18
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from dxm.lib.masking_api.api_client import ApiClient


class DatabaseRulesetApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def bulk_table_update(self, database_ruleset_id, body, **kwargs):  # noqa: E501
        """Update the set of tables and their attributes associated with a database ruleset in bulk  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.bulk_table_update(database_ruleset_id, body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int database_ruleset_id: The ID of the database ruleset to update the tables for (required)
        :param TableMetadataBulkInput body: The exact list of tables to put in the ruleset. Note that existing tables for this ruleset not in this list will be deleted (required)
        :return: AsyncTask
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.bulk_table_update_with_http_info(database_ruleset_id, body, **kwargs)  # noqa: E501
        else:
            (data) = self.bulk_table_update_with_http_info(database_ruleset_id, body, **kwargs)  # noqa: E501
            return data

    def bulk_table_update_with_http_info(self, database_ruleset_id, body, **kwargs):  # noqa: E501
        """Update the set of tables and their attributes associated with a database ruleset in bulk  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.bulk_table_update_with_http_info(database_ruleset_id, body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int database_ruleset_id: The ID of the database ruleset to update the tables for (required)
        :param TableMetadataBulkInput body: The exact list of tables to put in the ruleset. Note that existing tables for this ruleset not in this list will be deleted (required)
        :return: AsyncTask
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['database_ruleset_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method bulk_table_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'database_ruleset_id' is set
        if self.api_client.client_side_validation and ('database_ruleset_id' not in params or
                                                       params['database_ruleset_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `database_ruleset_id` when calling `bulk_table_update`")  # noqa: E501
        # verify the required parameter 'body' is set
        if self.api_client.client_side_validation and ('body' not in params or
                                                       params['body'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `body` when calling `bulk_table_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'database_ruleset_id' in params:
            path_params['databaseRulesetId'] = params['database_ruleset_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/database-rulesets/{databaseRulesetId}/bulk-table-update', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AsyncTask',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def copy_database_ruleset(self, database_ruleset_id, body, **kwargs):  # noqa: E501
        """Copy database ruleset by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.copy_database_ruleset(database_ruleset_id, body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int database_ruleset_id: The ID of the database ruleset to copy (required)
        :param DatabaseRulesetCopy body: The name of the ruleset. This must be unique within an environment. (required)
        :return: DatabaseRuleset
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.copy_database_ruleset_with_http_info(database_ruleset_id, body, **kwargs)  # noqa: E501
        else:
            (data) = self.copy_database_ruleset_with_http_info(database_ruleset_id, body, **kwargs)  # noqa: E501
            return data

    def copy_database_ruleset_with_http_info(self, database_ruleset_id, body, **kwargs):  # noqa: E501
        """Copy database ruleset by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.copy_database_ruleset_with_http_info(database_ruleset_id, body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int database_ruleset_id: The ID of the database ruleset to copy (required)
        :param DatabaseRulesetCopy body: The name of the ruleset. This must be unique within an environment. (required)
        :return: DatabaseRuleset
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['database_ruleset_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method copy_database_ruleset" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'database_ruleset_id' is set
        if self.api_client.client_side_validation and ('database_ruleset_id' not in params or
                                                       params['database_ruleset_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `database_ruleset_id` when calling `copy_database_ruleset`")  # noqa: E501
        # verify the required parameter 'body' is set
        if self.api_client.client_side_validation and ('body' not in params or
                                                       params['body'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `body` when calling `copy_database_ruleset`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'database_ruleset_id' in params:
            path_params['databaseRulesetId'] = params['database_ruleset_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/database-rulesets/{databaseRulesetId}/copy', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='DatabaseRuleset',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_database_ruleset(self, body, **kwargs):  # noqa: E501
        """Create database ruleset  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_database_ruleset(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DatabaseRuleset body: The database ruleset to create (required)
        :return: DatabaseRuleset
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_database_ruleset_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.create_database_ruleset_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def create_database_ruleset_with_http_info(self, body, **kwargs):  # noqa: E501
        """Create database ruleset  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_database_ruleset_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DatabaseRuleset body: The database ruleset to create (required)
        :return: DatabaseRuleset
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_database_ruleset" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if self.api_client.client_side_validation and ('body' not in params or
                                                       params['body'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `body` when calling `create_database_ruleset`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/database-rulesets', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='DatabaseRuleset',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_database_ruleset(self, database_ruleset_id, **kwargs):  # noqa: E501
        """Delete database ruleset by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_database_ruleset(database_ruleset_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int database_ruleset_id: The ID of the database ruleset to delete (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_database_ruleset_with_http_info(database_ruleset_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_database_ruleset_with_http_info(database_ruleset_id, **kwargs)  # noqa: E501
            return data

    def delete_database_ruleset_with_http_info(self, database_ruleset_id, **kwargs):  # noqa: E501
        """Delete database ruleset by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_database_ruleset_with_http_info(database_ruleset_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int database_ruleset_id: The ID of the database ruleset to delete (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['database_ruleset_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_database_ruleset" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'database_ruleset_id' is set
        if self.api_client.client_side_validation and ('database_ruleset_id' not in params or
                                                       params['database_ruleset_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `database_ruleset_id` when calling `delete_database_ruleset`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'database_ruleset_id' in params:
            path_params['databaseRulesetId'] = params['database_ruleset_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/database-rulesets/{databaseRulesetId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_all_database_rulesets(self, **kwargs):  # noqa: E501
        """Get all database rulesets  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_database_rulesets(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int environment_id: The ID of the environment to get all database rulesets from
        :param int page_number: The page number for which to get database rulesets. This will default to the first page if excluded
        :param int page_size: The maximum number of objects to return. This will default to the DEFAULT_API_PAGE_SIZE property if not provided
        :return: DatabaseRulesetList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_all_database_rulesets_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_all_database_rulesets_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_all_database_rulesets_with_http_info(self, **kwargs):  # noqa: E501
        """Get all database rulesets  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_database_rulesets_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int environment_id: The ID of the environment to get all database rulesets from
        :param int page_number: The page number for which to get database rulesets. This will default to the first page if excluded
        :param int page_size: The maximum number of objects to return. This will default to the DEFAULT_API_PAGE_SIZE property if not provided
        :return: DatabaseRulesetList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['environment_id', 'page_number', 'page_size']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_database_rulesets" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'environment_id' in params:
            query_params.append(('environment_id', params['environment_id']))  # noqa: E501
        if 'page_number' in params:
            query_params.append(('page_number', params['page_number']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/database-rulesets', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='DatabaseRulesetList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_database_ruleset_by_id(self, database_ruleset_id, **kwargs):  # noqa: E501
        """Get database ruleset by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_database_ruleset_by_id(database_ruleset_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int database_ruleset_id: The ID of the database ruleset to get (required)
        :return: DatabaseRuleset
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_database_ruleset_by_id_with_http_info(database_ruleset_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_database_ruleset_by_id_with_http_info(database_ruleset_id, **kwargs)  # noqa: E501
            return data

    def get_database_ruleset_by_id_with_http_info(self, database_ruleset_id, **kwargs):  # noqa: E501
        """Get database ruleset by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_database_ruleset_by_id_with_http_info(database_ruleset_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int database_ruleset_id: The ID of the database ruleset to get (required)
        :return: DatabaseRuleset
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['database_ruleset_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_database_ruleset_by_id" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'database_ruleset_id' is set
        if self.api_client.client_side_validation and ('database_ruleset_id' not in params or
                                                       params['database_ruleset_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `database_ruleset_id` when calling `get_database_ruleset_by_id`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'database_ruleset_id' in params:
            path_params['databaseRulesetId'] = params['database_ruleset_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/database-rulesets/{databaseRulesetId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='DatabaseRuleset',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def refresh_database_ruleset(self, database_ruleset_id, **kwargs):  # noqa: E501
        """Refresh database ruleset by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.refresh_database_ruleset(database_ruleset_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int database_ruleset_id: The ID of the database ruleset to refresh (required)
        :return: AsyncTask
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.refresh_database_ruleset_with_http_info(database_ruleset_id, **kwargs)  # noqa: E501
        else:
            (data) = self.refresh_database_ruleset_with_http_info(database_ruleset_id, **kwargs)  # noqa: E501
            return data

    def refresh_database_ruleset_with_http_info(self, database_ruleset_id, **kwargs):  # noqa: E501
        """Refresh database ruleset by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.refresh_database_ruleset_with_http_info(database_ruleset_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int database_ruleset_id: The ID of the database ruleset to refresh (required)
        :return: AsyncTask
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['database_ruleset_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method refresh_database_ruleset" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'database_ruleset_id' is set
        if self.api_client.client_side_validation and ('database_ruleset_id' not in params or
                                                       params['database_ruleset_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `database_ruleset_id` when calling `refresh_database_ruleset`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'database_ruleset_id' in params:
            path_params['databaseRulesetId'] = params['database_ruleset_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/database-rulesets/{databaseRulesetId}/refresh', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AsyncTask',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_database_ruleset(self, database_ruleset_id, body, **kwargs):  # noqa: E501
        """Update database ruleset  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_database_ruleset(database_ruleset_id, body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int database_ruleset_id: The ID of the database ruleset to update (required)
        :param DatabaseRuleset body: The updated form of the database ruleset (required)
        :return: DatabaseRuleset
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_database_ruleset_with_http_info(database_ruleset_id, body, **kwargs)  # noqa: E501
        else:
            (data) = self.update_database_ruleset_with_http_info(database_ruleset_id, body, **kwargs)  # noqa: E501
            return data

    def update_database_ruleset_with_http_info(self, database_ruleset_id, body, **kwargs):  # noqa: E501
        """Update database ruleset  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_database_ruleset_with_http_info(database_ruleset_id, body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int database_ruleset_id: The ID of the database ruleset to update (required)
        :param DatabaseRuleset body: The updated form of the database ruleset (required)
        :return: DatabaseRuleset
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['database_ruleset_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_database_ruleset" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'database_ruleset_id' is set
        if self.api_client.client_side_validation and ('database_ruleset_id' not in params or
                                                       params['database_ruleset_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `database_ruleset_id` when calling `update_database_ruleset`")  # noqa: E501
        # verify the required parameter 'body' is set
        if self.api_client.client_side_validation and ('body' not in params or
                                                       params['body'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `body` when calling `update_database_ruleset`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'database_ruleset_id' in params:
            path_params['databaseRulesetId'] = params['database_ruleset_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/database-rulesets/{databaseRulesetId}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='DatabaseRuleset',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
