# coding: utf-8

"""
    Masking API

    Schema for the Continuous Compliance Engine API  # noqa: E501

    OpenAPI spec version: 5.1.18
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from dxm.lib.masking_api.api_client import ApiClient


class FileFormatApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_file_format(self, file_format, file_format_type, **kwargs):  # noqa: E501
        """Create file format  # noqa: E501

        WARNING: The generated curl command is incorrect, so please refer to the Masking API guide for instructions on how to upload files through the API  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_file_format(file_format, file_format_type, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param file file_format: The file format to be uploaded. The logical name of the file format will be exactly the name of this uploaded file (required)
        :param str file_format_type: The type of the file format being uploaded (required)
        :return: FileFormat
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_file_format_with_http_info(file_format, file_format_type, **kwargs)  # noqa: E501
        else:
            (data) = self.create_file_format_with_http_info(file_format, file_format_type, **kwargs)  # noqa: E501
            return data

    def create_file_format_with_http_info(self, file_format, file_format_type, **kwargs):  # noqa: E501
        """Create file format  # noqa: E501

        WARNING: The generated curl command is incorrect, so please refer to the Masking API guide for instructions on how to upload files through the API  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_file_format_with_http_info(file_format, file_format_type, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param file file_format: The file format to be uploaded. The logical name of the file format will be exactly the name of this uploaded file (required)
        :param str file_format_type: The type of the file format being uploaded (required)
        :return: FileFormat
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['file_format', 'file_format_type']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_file_format" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'file_format' is set
        if self.api_client.client_side_validation and ('file_format' not in params or
                                                       params['file_format'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `file_format` when calling `create_file_format`")  # noqa: E501
        # verify the required parameter 'file_format_type' is set
        if self.api_client.client_side_validation and ('file_format_type' not in params or
                                                       params['file_format_type'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `file_format_type` when calling `create_file_format`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'file_format' in params:
            local_var_files['fileFormat'] = params['file_format']  # noqa: E501
        if 'file_format_type' in params:
            form_params.append(('fileFormatType', params['file_format_type']))  # noqa: E501

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/file-formats', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='FileFormat',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_file_format(self, file_format_id, **kwargs):  # noqa: E501
        """Delete file format by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_file_format(file_format_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int file_format_id: The ID of the file format to delete (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_file_format_with_http_info(file_format_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_file_format_with_http_info(file_format_id, **kwargs)  # noqa: E501
            return data

    def delete_file_format_with_http_info(self, file_format_id, **kwargs):  # noqa: E501
        """Delete file format by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_file_format_with_http_info(file_format_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int file_format_id: The ID of the file format to delete (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['file_format_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_file_format" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'file_format_id' is set
        if self.api_client.client_side_validation and ('file_format_id' not in params or
                                                       params['file_format_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `file_format_id` when calling `delete_file_format`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'file_format_id' in params:
            path_params['fileFormatId'] = params['file_format_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/file-formats/{fileFormatId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_all_file_formats(self, **kwargs):  # noqa: E501
        """Get all file formats  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_file_formats(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page_number: The page number for which to get file formats. This will default to the first page if excluded
        :param int page_size: The maximum number of objects to return. This will default to the DEFAULT_API_PAGE_SIZE property if not provided
        :return: FileFormatList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_all_file_formats_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_all_file_formats_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_all_file_formats_with_http_info(self, **kwargs):  # noqa: E501
        """Get all file formats  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_file_formats_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page_number: The page number for which to get file formats. This will default to the first page if excluded
        :param int page_size: The maximum number of objects to return. This will default to the DEFAULT_API_PAGE_SIZE property if not provided
        :return: FileFormatList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['page_number', 'page_size']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_file_formats" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'page_number' in params:
            query_params.append(('page_number', params['page_number']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/file-formats', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='FileFormatList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_file_format_by_id(self, file_format_id, **kwargs):  # noqa: E501
        """Get file format by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_file_format_by_id(file_format_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int file_format_id: The ID of the file format to get (required)
        :return: FileFormat
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_file_format_by_id_with_http_info(file_format_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_file_format_by_id_with_http_info(file_format_id, **kwargs)  # noqa: E501
            return data

    def get_file_format_by_id_with_http_info(self, file_format_id, **kwargs):  # noqa: E501
        """Get file format by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_file_format_by_id_with_http_info(file_format_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int file_format_id: The ID of the file format to get (required)
        :return: FileFormat
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['file_format_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_file_format_by_id" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'file_format_id' is set
        if self.api_client.client_side_validation and ('file_format_id' not in params or
                                                       params['file_format_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `file_format_id` when calling `get_file_format_by_id`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'file_format_id' in params:
            path_params['fileFormatId'] = params['file_format_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/file-formats/{fileFormatId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='FileFormat',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_file_format(self, file_format_id, body, **kwargs):  # noqa: E501
        """Update file format  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_file_format(file_format_id, body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int file_format_id: The ID of the file format to update (required)
        :param FileFormat body: The updated file format (required)
        :return: FileFormat
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_file_format_with_http_info(file_format_id, body, **kwargs)  # noqa: E501
        else:
            (data) = self.update_file_format_with_http_info(file_format_id, body, **kwargs)  # noqa: E501
            return data

    def update_file_format_with_http_info(self, file_format_id, body, **kwargs):  # noqa: E501
        """Update file format  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_file_format_with_http_info(file_format_id, body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int file_format_id: The ID of the file format to update (required)
        :param FileFormat body: The updated file format (required)
        :return: FileFormat
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['file_format_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_file_format" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'file_format_id' is set
        if self.api_client.client_side_validation and ('file_format_id' not in params or
                                                       params['file_format_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `file_format_id` when calling `update_file_format`")  # noqa: E501
        # verify the required parameter 'body' is set
        if self.api_client.client_side_validation and ('body' not in params or
                                                       params['body'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `body` when calling `update_file_format`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'file_format_id' in params:
            path_params['fileFormatId'] = params['file_format_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/file-formats/{fileFormatId}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='FileFormat',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
