# coding: utf-8

"""
    Masking API

    Schema for the Masking Engine API  # noqa: E501

    OpenAPI spec version: 5.1.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from dxm.lib.masking_api.api_client import ApiClient


class JvmPermissionApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_all_jvm_permission_action(self, **kwargs):  # noqa: E501
        """Get all jvm permission actions  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_jvm_permission_action(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page_number: The page number for which to get permission actions. This will default to the first page if excluded
        :param int page_size: The maximum number of objects to return. This will default to the DEFAULT_API_PAGE_SIZE property if not provided
        :param str jvm_permission_class_name: The permission class name for which to get the actions for.
        :return: JvmPermissionActionsList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_all_jvm_permission_action_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_all_jvm_permission_action_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_all_jvm_permission_action_with_http_info(self, **kwargs):  # noqa: E501
        """Get all jvm permission actions  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_jvm_permission_action_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page_number: The page number for which to get permission actions. This will default to the first page if excluded
        :param int page_size: The maximum number of objects to return. This will default to the DEFAULT_API_PAGE_SIZE property if not provided
        :param str jvm_permission_class_name: The permission class name for which to get the actions for.
        :return: JvmPermissionActionsList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['page_number', 'page_size', 'jvm_permission_class_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_jvm_permission_action" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'page_number' in params:
            query_params.append(('page_number', params['page_number']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501
        if 'jvm_permission_class_name' in params:
            query_params.append(('jvm_permission_class_name', params['jvm_permission_class_name']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/jvm-permission-actions', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JvmPermissionActionsList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_all_jvm_permission_class_name(self, **kwargs):  # noqa: E501
        """Get all jvm permission class names  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_jvm_permission_class_name(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page_number: The page number for which to get permission class names. This will default to the first page if excluded
        :param int page_size: The maximum number of objects to return. This will default to the DEFAULT_API_PAGE_SIZE property if not provided
        :return: JvmPermissionClassNamesList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_all_jvm_permission_class_name_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_all_jvm_permission_class_name_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_all_jvm_permission_class_name_with_http_info(self, **kwargs):  # noqa: E501
        """Get all jvm permission class names  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_jvm_permission_class_name_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page_number: The page number for which to get permission class names. This will default to the first page if excluded
        :param int page_size: The maximum number of objects to return. This will default to the DEFAULT_API_PAGE_SIZE property if not provided
        :return: JvmPermissionClassNamesList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['page_number', 'page_size']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_jvm_permission_class_name" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'page_number' in params:
            query_params.append(('page_number', params['page_number']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/jvm-permission-class-names', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JvmPermissionClassNamesList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_all_jvm_permission_target_name(self, **kwargs):  # noqa: E501
        """Get all jvm permission target names  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_jvm_permission_target_name(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page_number: The page number for which to get permission target names. This will default to the first page if excluded
        :param int page_size: The maximum number of objects to return. This will default to the DEFAULT_API_PAGE_SIZE property if not provided
        :param str jvm_permission_class_name: The permission class name for which to get the target names for.
        :return: JvmPermissionTargetNamesList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_all_jvm_permission_target_name_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_all_jvm_permission_target_name_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_all_jvm_permission_target_name_with_http_info(self, **kwargs):  # noqa: E501
        """Get all jvm permission target names  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_jvm_permission_target_name_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page_number: The page number for which to get permission target names. This will default to the first page if excluded
        :param int page_size: The maximum number of objects to return. This will default to the DEFAULT_API_PAGE_SIZE property if not provided
        :param str jvm_permission_class_name: The permission class name for which to get the target names for.
        :return: JvmPermissionTargetNamesList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['page_number', 'page_size', 'jvm_permission_class_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_jvm_permission_target_name" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'page_number' in params:
            query_params.append(('page_number', params['page_number']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501
        if 'jvm_permission_class_name' in params:
            query_params.append(('jvm_permission_class_name', params['jvm_permission_class_name']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/jvm-permission-target-names', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JvmPermissionTargetNamesList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_jvm_permission_action_by_id(self, jvm_permission_action_id, **kwargs):  # noqa: E501
        """Get jvm permission action by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_jvm_permission_action_by_id(jvm_permission_action_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int jvm_permission_action_id: The ID of the permission action to get (required)
        :return: JvmPermissionAction
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_jvm_permission_action_by_id_with_http_info(jvm_permission_action_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_jvm_permission_action_by_id_with_http_info(jvm_permission_action_id, **kwargs)  # noqa: E501
            return data

    def get_jvm_permission_action_by_id_with_http_info(self, jvm_permission_action_id, **kwargs):  # noqa: E501
        """Get jvm permission action by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_jvm_permission_action_by_id_with_http_info(jvm_permission_action_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int jvm_permission_action_id: The ID of the permission action to get (required)
        :return: JvmPermissionAction
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['jvm_permission_action_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_jvm_permission_action_by_id" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'jvm_permission_action_id' is set
        if self.api_client.client_side_validation and ('jvm_permission_action_id' not in params or
                                                       params['jvm_permission_action_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `jvm_permission_action_id` when calling `get_jvm_permission_action_by_id`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'jvm_permission_action_id' in params:
            path_params['jvmPermissionActionId'] = params['jvm_permission_action_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/jvm-permission-actions/{jvmPermissionActionId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JvmPermissionAction',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_jvm_permission_class_name_by_id(self, jvm_permission_class_name_id, **kwargs):  # noqa: E501
        """Get jvm permission class names by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_jvm_permission_class_name_by_id(jvm_permission_class_name_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int jvm_permission_class_name_id: The ID of the permission class name to get (required)
        :return: JvmPermissionClassName
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_jvm_permission_class_name_by_id_with_http_info(jvm_permission_class_name_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_jvm_permission_class_name_by_id_with_http_info(jvm_permission_class_name_id, **kwargs)  # noqa: E501
            return data

    def get_jvm_permission_class_name_by_id_with_http_info(self, jvm_permission_class_name_id, **kwargs):  # noqa: E501
        """Get jvm permission class names by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_jvm_permission_class_name_by_id_with_http_info(jvm_permission_class_name_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int jvm_permission_class_name_id: The ID of the permission class name to get (required)
        :return: JvmPermissionClassName
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['jvm_permission_class_name_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_jvm_permission_class_name_by_id" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'jvm_permission_class_name_id' is set
        if self.api_client.client_side_validation and ('jvm_permission_class_name_id' not in params or
                                                       params['jvm_permission_class_name_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `jvm_permission_class_name_id` when calling `get_jvm_permission_class_name_by_id`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'jvm_permission_class_name_id' in params:
            path_params['jvmPermissionClassNameId'] = params['jvm_permission_class_name_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/jvm-permission-class-names/{jvmPermissionClassNameId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JvmPermissionClassName',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_jvm_permission_target_name_by_id(self, jvm_permission_target_name_id, **kwargs):  # noqa: E501
        """Get jvm permission target name by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_jvm_permission_target_name_by_id(jvm_permission_target_name_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int jvm_permission_target_name_id: The ID of the permission target name to get (required)
        :return: JvmPermissionTargetName
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_jvm_permission_target_name_by_id_with_http_info(jvm_permission_target_name_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_jvm_permission_target_name_by_id_with_http_info(jvm_permission_target_name_id, **kwargs)  # noqa: E501
            return data

    def get_jvm_permission_target_name_by_id_with_http_info(self, jvm_permission_target_name_id, **kwargs):  # noqa: E501
        """Get jvm permission target name by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_jvm_permission_target_name_by_id_with_http_info(jvm_permission_target_name_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int jvm_permission_target_name_id: The ID of the permission target name to get (required)
        :return: JvmPermissionTargetName
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['jvm_permission_target_name_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_jvm_permission_target_name_by_id" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'jvm_permission_target_name_id' is set
        if self.api_client.client_side_validation and ('jvm_permission_target_name_id' not in params or
                                                       params['jvm_permission_target_name_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `jvm_permission_target_name_id` when calling `get_jvm_permission_target_name_by_id`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'jvm_permission_target_name_id' in params:
            path_params['jvmPermissionTargetNameId'] = params['jvm_permission_target_name_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/jvm-permission-target-names/{jvmPermissionTargetNameId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='JvmPermissionTargetName',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
