# coding: utf-8

"""
    Masking API

    Schema for the Masking Engine API  # noqa: E501

    OpenAPI spec version: 5.1.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from dxm.lib.masking_api.api_client import ApiClient


class MountFilesystemApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def connect_mount_filesystem(self, mount_id, **kwargs):  # noqa: E501
        """Connect filesystem mount  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.connect_mount_filesystem(mount_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int mount_id: The ID of the mount to connect (required)
        :return: MountInformation
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.connect_mount_filesystem_with_http_info(mount_id, **kwargs)  # noqa: E501
        else:
            (data) = self.connect_mount_filesystem_with_http_info(mount_id, **kwargs)  # noqa: E501
            return data

    def connect_mount_filesystem_with_http_info(self, mount_id, **kwargs):  # noqa: E501
        """Connect filesystem mount  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.connect_mount_filesystem_with_http_info(mount_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int mount_id: The ID of the mount to connect (required)
        :return: MountInformation
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['mount_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method connect_mount_filesystem" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'mount_id' is set
        if self.api_client.client_side_validation and ('mount_id' not in params or
                                                       params['mount_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `mount_id` when calling `connect_mount_filesystem`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'mount_id' in params:
            path_params['mountID'] = params['mount_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/mount-filesystem/{mountID}/connect', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MountInformation',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_mount_filesystem(self, body, **kwargs):  # noqa: E501
        """Create filesystem mount  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_mount_filesystem(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param MountInformation body: The filesystem to mount (required)
        :return: MountInformation
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_mount_filesystem_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.create_mount_filesystem_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def create_mount_filesystem_with_http_info(self, body, **kwargs):  # noqa: E501
        """Create filesystem mount  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_mount_filesystem_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param MountInformation body: The filesystem to mount (required)
        :return: MountInformation
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_mount_filesystem" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if self.api_client.client_side_validation and ('body' not in params or
                                                       params['body'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `body` when calling `create_mount_filesystem`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/mount-filesystem', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MountInformation',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_mount_filesystem(self, mount_id, **kwargs):  # noqa: E501
        """Delete filesystem mount  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_mount_filesystem(mount_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int mount_id: The ID of the mount to delete (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_mount_filesystem_with_http_info(mount_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_mount_filesystem_with_http_info(mount_id, **kwargs)  # noqa: E501
            return data

    def delete_mount_filesystem_with_http_info(self, mount_id, **kwargs):  # noqa: E501
        """Delete filesystem mount  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_mount_filesystem_with_http_info(mount_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int mount_id: The ID of the mount to delete (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['mount_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_mount_filesystem" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'mount_id' is set
        if self.api_client.client_side_validation and ('mount_id' not in params or
                                                       params['mount_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `mount_id` when calling `delete_mount_filesystem`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'mount_id' in params:
            path_params['mountID'] = params['mount_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/mount-filesystem/{mountID}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def disconnect_mount_filesystem(self, mount_id, **kwargs):  # noqa: E501
        """Disconnect filesystem mount  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.disconnect_mount_filesystem(mount_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int mount_id: The ID of the mount to disconnect (required)
        :return: MountInformation
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.disconnect_mount_filesystem_with_http_info(mount_id, **kwargs)  # noqa: E501
        else:
            (data) = self.disconnect_mount_filesystem_with_http_info(mount_id, **kwargs)  # noqa: E501
            return data

    def disconnect_mount_filesystem_with_http_info(self, mount_id, **kwargs):  # noqa: E501
        """Disconnect filesystem mount  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.disconnect_mount_filesystem_with_http_info(mount_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int mount_id: The ID of the mount to disconnect (required)
        :return: MountInformation
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['mount_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method disconnect_mount_filesystem" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'mount_id' is set
        if self.api_client.client_side_validation and ('mount_id' not in params or
                                                       params['mount_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `mount_id` when calling `disconnect_mount_filesystem`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'mount_id' in params:
            path_params['mountID'] = params['mount_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/mount-filesystem/{mountID}/disconnect', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MountInformation',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_all_mounts(self, **kwargs):  # noqa: E501
        """Get all mounts  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_mounts(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page_number: The page number for which to get mount information. This will default to the first page if excluded
        :param int page_size: The maximum number of objects to return. This will default to the DEFAULT_API_PAGE_SIZE property if not provided
        :return: MountInformationList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_all_mounts_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_all_mounts_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_all_mounts_with_http_info(self, **kwargs):  # noqa: E501
        """Get all mounts  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_mounts_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page_number: The page number for which to get mount information. This will default to the first page if excluded
        :param int page_size: The maximum number of objects to return. This will default to the DEFAULT_API_PAGE_SIZE property if not provided
        :return: MountInformationList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['page_number', 'page_size']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_mounts" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'page_number' in params:
            query_params.append(('page_number', params['page_number']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/mount-filesystem', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MountInformationList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_mount_by_id(self, mount_id, **kwargs):  # noqa: E501
        """Get mount by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_mount_by_id(mount_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int mount_id: The ID of the mount to get (required)
        :return: MountInformation
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_mount_by_id_with_http_info(mount_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_mount_by_id_with_http_info(mount_id, **kwargs)  # noqa: E501
            return data

    def get_mount_by_id_with_http_info(self, mount_id, **kwargs):  # noqa: E501
        """Get mount by ID  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_mount_by_id_with_http_info(mount_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int mount_id: The ID of the mount to get (required)
        :return: MountInformation
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['mount_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_mount_by_id" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'mount_id' is set
        if self.api_client.client_side_validation and ('mount_id' not in params or
                                                       params['mount_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `mount_id` when calling `get_mount_by_id`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'mount_id' in params:
            path_params['mountID'] = params['mount_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/mount-filesystem/{mountID}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MountInformation',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def remount_mount_filesystem(self, mount_id, body, **kwargs):  # noqa: E501
        """Remount filesystem mount  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.remount_mount_filesystem(mount_id, body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int mount_id: The ID of the mount to update (required)
        :param MountInformation body: The updated filesystem (required)
        :return: MountInformation
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.remount_mount_filesystem_with_http_info(mount_id, body, **kwargs)  # noqa: E501
        else:
            (data) = self.remount_mount_filesystem_with_http_info(mount_id, body, **kwargs)  # noqa: E501
            return data

    def remount_mount_filesystem_with_http_info(self, mount_id, body, **kwargs):  # noqa: E501
        """Remount filesystem mount  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.remount_mount_filesystem_with_http_info(mount_id, body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int mount_id: The ID of the mount to update (required)
        :param MountInformation body: The updated filesystem (required)
        :return: MountInformation
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['mount_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method remount_mount_filesystem" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'mount_id' is set
        if self.api_client.client_side_validation and ('mount_id' not in params or
                                                       params['mount_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `mount_id` when calling `remount_mount_filesystem`")  # noqa: E501
        # verify the required parameter 'body' is set
        if self.api_client.client_side_validation and ('body' not in params or
                                                       params['body'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `body` when calling `remount_mount_filesystem`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'mount_id' in params:
            path_params['mountID'] = params['mount_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/mount-filesystem/{mountID}/remount', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MountInformation',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_mount_filesystem(self, mount_id, body, **kwargs):  # noqa: E501
        """Update filesystem mount  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_mount_filesystem(mount_id, body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int mount_id: The ID of the mount to update (required)
        :param MountInformation body: The updated filesystem (required)
        :return: MountInformation
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_mount_filesystem_with_http_info(mount_id, body, **kwargs)  # noqa: E501
        else:
            (data) = self.update_mount_filesystem_with_http_info(mount_id, body, **kwargs)  # noqa: E501
            return data

    def update_mount_filesystem_with_http_info(self, mount_id, body, **kwargs):  # noqa: E501
        """Update filesystem mount  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_mount_filesystem_with_http_info(mount_id, body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int mount_id: The ID of the mount to update (required)
        :param MountInformation body: The updated filesystem (required)
        :return: MountInformation
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['mount_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_mount_filesystem" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'mount_id' is set
        if self.api_client.client_side_validation and ('mount_id' not in params or
                                                       params['mount_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `mount_id` when calling `update_mount_filesystem`")  # noqa: E501
        # verify the required parameter 'body' is set
        if self.api_client.client_side_validation and ('body' not in params or
                                                       params['body'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `body` when calling `update_mount_filesystem`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'mount_id' in params:
            path_params['mountID'] = params['mount_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/mount-filesystem/{mountID}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MountInformation',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
